# This GitHub workflow deploys Bundle resources (ML resource config and more)
# defined under databricks_test/databricks-resources/*
# and databricks_test/bundle.yml with staging deployment target configs,
# when PRs are merged into the default branch
name: Bundle Deployment for databricks-test Staging

on:
  push:
    branches:
      - 'develop'
  workflow_dispatch:

defaults:
  run:
    working-directory: ./databricks_test

env:
  DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
  DATABRICKS_URL: ${{ secrets.DATABRICKS_URL }}

jobs:
  staging:
    concurrency: databricks-test-staging-bundle-job
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: databricks/setup-cli@main
      - name: Validate Bundle For Staging
        id: validate
        run: |
          databricks bundle validate -t staging
      - name: Deploy Bundle to Staging
        id: deploy
        run: |
          databricks bundle deploy -t staging
