# This GitHub workflow deploys Bundle resources (ML resource config and more)
# defined under databricks_test/databricks-resources/*
# and databricks_test/bundle.yml with prod deployment target configs,
# when PRs are merged into the release branch
name: Bundle Deployment for databricks-test Prod

on:
  push:
    branches:
      - 'master'
  workflow_dispatch:

defaults:
  run:
    working-directory: ./databricks_test

env:
  DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
  DATABRICKS_URL: ${{ secrets.DATABRICKS_URL }}

jobs:
  prod:
    concurrency: databricks-test-prod-bundle-job
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: databricks/setup-cli@main
      - name: Validate Bundle For Prod
        id: validate
        run: |
          databricks bundle validate -t prod
      - name: Deploy Bundle to Prod
        id: deploy
        run: |
          databricks bundle deploy -t prod
